### ISSUE TITLE
Blank Optional<String> values are serialized for JsonInclude.NON_EMPTY

### ISSUE THREAD

**Issue by jlorenzen** [FasterXML/jackson-datatype-jdk8#18]
I'm trying to configure my POJO to exclude blank Optional Strings, `Optional.of("")`, but it continues to be included when serialized.
It looked like #8 should have resolved this issue but I'm running with jackson 2.6.2 and it's still returning blank optional strings. I've set `@JsonInclude(JsonInclude.NON_EMPTY` on the field as well.

I've written a failing test for this use case: https://github.com/FasterXML/jackson-datatype-jdk8/pull/17

**Comment by cowtowncoder** [comment]
Quick question: when you say "be included when deserialized", I presume you mean "when serialized"?

**Comment by jlorenzen** [comment]
Sorry yes.

**Comment by cowtowncoder** [comment]
Oh, one quick note: `NON_ABSENT` would not work here, since `Optional.of("")` is actually present isn't it? Would `NON_EMPTY` work here?

Also note that there is some planned work to support new (as of Jackson 2.5) property, so that:

     @JsonInclude(value=Include.NON_ABSENT, content=Include.NON_EMPTY)

would allow you to tackle the difference between container (`Optional`, `List`, `Map`), and its contents.
But I don't think that has yet been implemented for `Optional`s....
One more item to work on for 2.7 (and maybe backport in 2.6 if low risk).

**Comment by jlorenzen** [comment]
I added `NON_EMPTY` in the test and it still serializes it. Is there anything that can be done to make it so it doesn't serialize it if the contents are empty?

**Comment by cowtowncoder** [comment]
Ok first, scratch my first idea; `content` would not help here, it can only work with `Collection`s, `Map`s and arrays, as it can block serialization of contents but not container itself.

`NON_EMPTY`, however, should work here: it should check for "emptiness" of value contained.

**Comment by jlorenzen** [comment]
This fails:
```java
ObjectMapper mapper = mapperWithModule()
        .setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
assertEquals(aposToQuotes("{}"),
        mapper.writeValueAsString(new OptionalStringBean("")));
```

**Comment by cowtowncoder** [comment]
Yes. I was wrong with my initial thinking it could work -- it won't. `NON_EMPTY` does not and will not work for `Optional`. Until `content=Include.NON_EMPTY` is supported, you will need a custom serializer for `Optional`s, possibly sub-classing default one module uses.

**Comment by jlorenzen** [comment]
When you say `Until content=Include.NON_EMPTY is supported` do you mean until it's supported in the jdk8 module?

**Comment by cowtowncoder** [comment]
Yes, it needs to be supported via jdk8 module as handling relies on information serializer provides.

But you can register custom serializer in the meantime, as it need to go through somewhat complex process of piping through all the information -- in your case you can use it just for `Optional<String>` case and simplify accordingly. `isEmpty()` is the method called by `NON_EMPTY` and `NON_ABSENT` (although in latter case only if type is `ReferentialType`, new subtype of 2.6).

**Comment by jlorenzen** [comment]
Sorry for the dumb question but can you point me to some documentation or provide some pseudo code on how to register a custom serializer? And I'm assuming I'd still want to register the `Jdk8Module` right?

**Comment by cowtowncoder** [comment]
You may want to look at `Jdk8Module` itself for registration. Or, use `@JsonDeserialize(using=MyOptionalStringDeserializer.class)` if it's just one or two instances, and avoid module.

**Comment by jlorenzen** [comment]
Yeah taking a look at those, I see `Jdk8Module` calls `context.addSerializers(new Jdk8Serializers())`. `Jdk8Serializers` then has a few if/else's and I'm not sure I'm going to be able to match on `Optional<String>.class`. So I'm not confident I could register a serializer for it.

**Comment by cowtowncoder** [comment]
It depends on how you register things, but the `JavaType` for `Optional` will be of `ReferenceType`, and does indeed give access to contained type. Or, if you prefer, just directly register the deserializer for property using annotation, in which case you do not have to do matching indirectly.

Anyway, those are the current options that can be made to work.

**Comment by jlorenzen** [comment]
Will this work?
```java
public class OptionalStringSerializer extends StdSerializer<Optional<String>> {
    public OptionalStringSerializer() {
        super(Optional.class, true);
    }
```

**Comment by jlorenzen** [comment]
So I got pretty close but my new `Optional<String>` Serializer gets called for `Optional<Long>` values as well. I'm guessing this is because I'm passing `Optional.class` to the `StdSerializer` in my constructor.
I'm not sure how I can fix that; got any ideas? I also need to register this globally with the mapper.

**Comment by jlorenzen** [comment]
@cowtowncoder I actually dug a little more and put in a _fix_ for `OptionalSerializer` to handle this. Would you mind taking a look and seeing if it's something you wouldn't mind merging back into the project? https://github.com/FasterXML/jackson-datatype-jdk8/pull/17

**Comment by cowtowncoder** [comment]
Ok, so, use of annotation

    @JsonInclude(content=Include.NON_EMPTY)

(and various other values, `NON_ABSENT``, `NON_NULL`, where applicable -- although for `String`, `NON_EMPTY` is sensible)

will not work as expected. This means that

    @JsonInclude(value=Include_NON_EMPTY)

requires value to be missing, whereas property `content=Include.[VALUE]` refers to additional constraint on referenced value.

Now: I realize that this is not as convenient as a global setting would be. I am open to alternative improvements in `jackson-databind`.

**Comment by jlorenzen** [comment]
@cowtowncoder So if an `Optional<String>` field is annotated with `@JsonInclude(value=Include.NON_EMPTY, content=Include.NON_EMPTY)` jackson will exclude it if it's a blank string?

**Comment by cowtowncoder** [comment]
Yes.

I am also working on actually allowing use of `JsonInclude.Value` (instead of `JsonInclude.Include`) for default serialization inclusion: this would allow making this actual global setting, as you can specify both "value" and "content" inclusion, just like with annotation.

**Comment by dcbasso** [comment]
Did you resolve it?
Here I could not fix the problem.

**Comment by dcbasso** [comment]
I found my problem:

I need to override the "isEmpty()"  from **extends StdSerializer<List<MyCustomClass>>**, (check JsonSerializer method to override.).
When my StdSerializer extends from a List the default "isEmpty" appears not check is the list is empty...
@cowtowncoder that´s correct?
Thanks for your time.

**Comment by dcbasso** [comment]
Please check this:
`/**
     * Method called to check whether given serializable value is
     * considered "empty" value (for purposes of suppressing serialization
     * of empty values).
     *<p>
     * Default implementation will consider only null values to be empty.
     *<p>
     * NOTE: replaces {@link #isEmpty(Object)}, which was deprecated in 2.5
     * 
     * @since 2.5
     */
    public boolean isEmpty(SerializerProvider provider, T value) {
        return (value == null);
    }

This checks only is the GenericType Object (T value) is null, does not check if is a List and if this List is empty.

**Comment by cowtowncoder** [comment]
@dcbasso I am not quite sure what to look in there: `StdSerializer` can not check for anything else: it knows nothing about type it will be used for. Subtypes must implement functionality regarding logical "empty" value for type, if any, above and beyond `null` (which is always considered empty, due to legacy reasons -- but check itself is something done by caller, or containing `Map`, array or `Collection`).

So you are right wrt solution; custom serializers do need to add support to interact with `NON_EMPTY` handling.

**Comment by dcbasso** [comment]
Hi @cowtowncoder how can we improve in JsonSerializer the method "isEmpty()" to get a better implementation for empty collections?
Please Suggest to me I can make the branch, change the code, commit and ask make a pull request!
Thanks a lot.

**Comment by dcbasso** [comment]
I suggest something like this:

```
/**
     * Method called to check whether given serializable value is
     * considered "empty" value (for purposes of suppressing serialization
     * of empty values).
     *<p>
     * Default implementation will consider only null values to be empty.
     *<p>
     * NOTE: replaces {@link #isEmpty(Object)}, which was deprecated in 2.5
     * 
     * @since 2.5
     */
    public boolean isEmpty(SerializerProvider provider, T value) {
        if (value == null) {
            return true;
        } else {
            if (value instanceof Collection) {
                Collection c = (Collection) value;
                return c.isEmpty();
            } 
            return false;
        }
    }
```

**Comment by cowtowncoder** [comment]
@dcbasso No. I appreciate your trying to help, but this is not how serializers should work: base class should usually not make assumptions of what subtypes might do, based on Java type.
It is up to collection serializers to add semantics, as `StdSerializer` is base for everything and we do not want to add deep coupling from generic base type to assumed behavior of subtypes.
Doing so would defeat the purpose of specialization by sub-classing, since full list of even just default empty checks is much bigger than this (Maps are easy, but reference type like `Optional` would require specific types, like Java 8 / Scala / Guava optionals; arrays are difficult to check in generic fashion).

So although I do see how this could simplify life slightly for specific case of Collection serializers, the general idea is that type-specific defaulting should be done at proper level in hierarchy. In case of `Collection`s, Implementation of `isEmpty()` exists in `CollectionSerializer`, as this is the first serializer type known to handle `Collection`s. If you want to implement your own collection serializer. Same is true to map, array and reference types.

I hope this makes more sense.

**Comment by dcbasso** [comment]
That´s nice. Sorry to bother you.
Thanks for your answer.

**Comment by cowtowncoder** [comment]
@dcbasso No problem at all -- I appreciate suggestions and help. And thank you for describing the idea as well. I hope to work together on other issues.
