### ISSUE TITLE
OptionalBooleanDeserializer Missing

### ISSUE THREAD

**Issue by brunoschuermans** [FasterXML/jackson-datatype-jdk8#23]
Until now we can't deserialize a bean with an Optional\<Boolean\>

```java
class MyBean {
  private Optional\<Boolean\> myOptionalBooleanProperty;
}
```
An OptionalBooleanDeserializer should be created like for Int/Long/Double

**Comment by cowtowncoder** [comment]
There is no type `OptionalBoolean`, unlike that of `OptionalLong` (etc), so there is no need for any special handling. Basic `Optional` serializer and deserializer should work just fine.

What problem are you having? Can you share a unit test that shows the problem you are having? (and with what version(s)?)

**Comment by brunoschuermans** [comment]
I give you several examples:

* when you have a null property in javascript (json) -> you get a null in the mapped java Object instead of an Optional.empty()
* when you have an empty String in javascript ("") -> you get an Optional.of("") instead of an Optional<String>.empty()
* when you have an empty Boolean in javascript -> you get a NullPointerException instead of an Optional<Boolean>.empty()

**Comment by cowtowncoder** [comment]
@brunoschuermans I am not sure I follow you -- how is javascript relevant here? Do you mean JSON content? When and  how do you get `NullPointerException`? What is empty `Boolean` (there's `null`, and `false` possibilities; but JSON has no Optional types.

As I said, properties with `Optional<Boolean>` should work just like any other type with `Optional` -- it is just a composition of `Optional`. If it does not, I need to know POJO used and code invoked. This is easiest by showing a simple unit test or code snippet.
And I need to know which version you are testing with it, because

**Comment by brunoschuermans** [comment]
The problem for the Boolean is at OptionalDeserializer:102
It doen't accept a null value for a Boolean property because you are using Optional.of() instead of Optional.ofNullable()

So what I'm expecting with the jdk8 datatype package is from a json input:

{
myEmptyString: "";
myEmptyBoolean: "";
}

is to get the following Deserialized Java Bean:

class MyBean {
  private Optional<String> myEmptyString = Optional.empty();
  private Optional<Boolean> myEmptyBoolean = Optional.empty();
}

Actually this is not the case

**Comment by cowtowncoder** [comment]
@brunoschuermans You still have not answered the most pertinent simple question I asked: what is the version?

Looking at code, 2.7.0-SNAPSHOT has this fixed, and if you had bothered to actually answer the question ("I can reproduce this with 2.6.3" or such), or, better yet, add the _simple reproduction_, we would have avoided wasting each other's time.

I will go ahead and change instantiation for 2.6 branch, and will try to write the unit test myself.
