### ISSUE TITLE
Request to support Optional field as null

### ISSUE THREAD

**Issue by nicechester** [FasterXML/jackson-datatype-jdk8#29]
Sometimes, we need to differentiate an explicit null field vs simply just missing field in JSON.
It could be done by null vs Optional.empty() in 2.5.x but the default behavior of Jdk8 module has been changed since 2.6.x.  Can you support this use case?
It might be done by some additional flag, parameter, or annotation.
See https://github.com/FasterXML/jackson-databind/issues/618#issuecomment-176313409 for reference.

**Comment by cowtowncoder** [comment]
I think this would be #11 wouldnt it?

**Comment by nicechester** [comment]
@cowtowncoder It seems like that change still treat null & Optional.empty() as same (omit serializing).

**Comment by cowtowncoder** [comment]
Then I do not understand what the expected behavior is? The other question is whether new values for `JsonInclude.Include` would help; there is now distinction between inclusion based on type itself (`Optional`, `List`, `Map`), and inclusion based on content type (value referred to by `Optional`; value(s), if any, of `List` etc). These should give much more flexibility for inclusion criteria, regarding `null` for `Optional`, or absent value within.
