### ISSUE TITLE
Unable to use "default typing" for values nested inside `Optional`

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-datatype-jdk8#3]
ObjectMapper.enableDefaultTyping() only serializes `Object` and non-concrete classes. `java.util.Optional` is both `final` and concrete, so its type does not get serialized.

I have the following questions:
1. How do I apply `@JsonTypeInfo` to a 3rd-party class like `java.util.Optional` which I cannot annotate directly?
2. How do I apply `@JsonTypeInfo` to value nested inside some class, like `java.util.Optional`, as opposed to the class itself?
3. Is it possible to make fix the default behavior provided by this module so `java.util.Optional` is serialized properly out-of-the-box?

**Comment by cowtowncoder** [comment]
Hmmh. Yes, I need to think about this.

**Comment by cowtowncoder** [comment]
On short term (at least before next minor release), I think you need to sub-class `ObjectMapper.DefaultTypeResolverBuilder` and override `useForType()`. Alternatively you could sub-class parent class `StdTypeResolverBuilder`.
Either way, that way you can figure out nominal type `Optional` refers to, and decide on type information need based on that, and not on wrapper type itself.

Longer term the way this could perhaps be supported would require defining either a new subtype of `JavaType`, or adding an accessor. I'll file an RFE for `jackson-databind`, since this would also be needed with, say, `AtomicReference`.

**Comment by cowtowncoder** [comment]
For what it is worth, polymorphic handling should work fine, if declared base type of value within `Optional` (for this test that would be `Task`) did have `@JsonTypeInfo`. Handling is fixed to work in 2.6.2, verified with unit tests.

**Comment by cowtowncoder** [comment]
I think this works at this point (2.8.4), closing.
Also, module moving to https://github.com/FasterXML/jackson-modules-java8
