### ISSUE TITLE
Optional mapping to preserve "empty" information

### ISSUE THREAD

**Issue by Grogdunn** [FasterXML/jackson-datatype-jdk8#30]
Hi,
the Optional are a "container" that can have 3 different states:
1. contains a value (eg: `Optional o = Optional.of("banana")`)
2. not contains a value (eg: `Optional o = Optional.empty()`)
3. is null (eg: `Optional o = null;`)

But with the current serialization the result are:
1.  `"banana"`
2. `null`
3. `null`

And the "empty" infromation is missing. I think a better (?) rappresentation would be:
1.  `["banana"]`
2. `[]`
3. `null`

What do you think?

Thanks in advance

**Comment by cowtowncoder** [comment]
I think you should look into handling of `@JsonInclude` to see if that could help you configure some aspects, especially regarding inclusion (or not) of `Optional` value without value.

As to use of wrapper array, that is not going to happen (at least by default): existing code and usage would break if such a change was made. But you can probably create your own `Module` that registers alternate serializer/deserializer to use output you would like.

Another potential future idea could be to actually allow such serialization, if annotation:

    @JsonFormat(shape=Shape.ARRAY)

which could be used to indicate this alternate notation. If you (or anyone else) wanted to work on adding such support I could help integrate it, along with merging it to Guava module, Scala module (both of which have Optional types of their own) and core databind for `AtomicReference`.

**Comment by CaptainMan** [comment]
While an empty Optional and null are a little different in how they behave, they represent the exact same concept. Optional exists to avoid worrying about how to handle null values as well as have "type-safe nulls".

Because an empty Optional and null are the same concept I think it is wrong to map them differently. I think it is especially wrong to map them in the way you suggest, though I do see where the idea is coming from.

**Comment by cowtowncoder** [comment]
At this point I consider it an Anti-Pattern to expose `Optional` externally, and in grand scheme of things have wasted way too much time to make it work. I wish I had basically let users who want to use it handle it exactly like they want, instead of trying to create one way to make it work.

But given that it has been implemented, the implementation of Jackson 2.7 is The One Way Optionals work in Jackson, by default, and no changes are contemplated. It is possible to add custom serializers, deserializers, so alternate behavior is possible for those who want that. But I have no interest in spending any more time for supporting feature that should never have been added in JDK. Optionals are huge PITA, and something Java as a language would be better without.

**Comment by cowtowncoder** [comment]
To clarify: I do not think I want to work more on Optionals support (minus bug fixes for existing behavior as necessary). I will still help others with contributions where those changes get support on mailing lists, and/or refer to other committers who may want to work on these issues.

**Comment by cowtowncoder** [comment]
@CaptainMan above comment not directly related to your comment (on which my stance is neutral) -- my original take was simply that it would be possible to allow for different representation if that was generally desired feature.
