### ISSUE TITLE
Optional serialisations breaks the default json properties order

### ISSUE THREAD

**Issue by tetv** [FasterXML/jackson-datatype-jdk8#38]
When there is a Optional property/field, then this field is realised to json first, breaking the natural order or the serialisation.

````java
public class Entity1 {
  public String getName() { ... };
  public @Nullable String getSurname { ... };
  // fields and constructor omitted to simplify
}

public class Entity2 {
  public String getName() { ... };
  public Optional<String> String getSurname { ... };
  // fields and constructor omitted to simplify
}
```
json produced for Entity1: `"{"name":"John", "surname":"Smith" }`
json produced for Entity2: `"{"surname":"Smith", "name":"John" }`

**Comment by cowtowncoder** [comment]
Order of fields/properties is not guaranteed since JVM does not guarantee any specific ordering. If you want to ensure specific ordering, you have to use `@JsonPropertyOrder` annotation`, or, if you want to enforce alphabetic ordering, enable `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY` on `ObjectMapper`.
