### ISSUE TITLE
null Optionals with missing parameter.

### ISSUE THREAD

**Issue by ReaperUnreal** [FasterXML/jackson-datatype-jdk8#6]
I know that this might not be fixable, but when there's a missing parameter in the JSON file, the deserialization defaults to not doing anything instead of setting it to Optional.empty().

It would be nice if this could be fixed so that I don't have to set everything to Optional.empty() in the declaration.

For example this JSON:

    {
        "value1": 2
    }

With the bean like so:

    public class TestBean {
        private int value1;
        private Optional<String> value2;
        public TestBean() {}
        public void setValue1(int value1) { this.value1 = value1; }
        public int getValue1() { return value1; }
        public void setValue2(Optional<String> value2) { this.value2 = values2; }
        public Optional<String> getValue2() { return value2; }
    }

Would deserialize such that `value1 = 2` and `value2 = null` whereas the desired behaviour would be `value2 = Optional.empty()`.

**Comment by cowtowncoder** [comment]
Unfortunately this is not possible without adding foundational support in `jackson-databind` for value defaulting -- currently only values that are found will have effect on objects.

But there is one exception to this handling: with Jackson 2.6, Creator parameters (parameters for constructor or factory method annotated with `@JsonCreator`), value defaulting will actually work, so that `getNullValue()` of matching deserializer is called for any creator property that was NOT found.

Put another way: this does work if (and only if) you use `@JsonCreator` annotated constructors, but not via setters or fields.

**Comment by andifant** [comment]
Would be a default value of `Optional.empty()` a possible solution?

```
public class TestBean {
    private int value1 = Optional.empty();
}
```

**Comment by cowtowncoder** [comment]
@andifant yes I think this is the simplest way to have defaulting in my opinion.

**Comment by ReaperUnreal** [comment]
@andifant Yes, that is what I ended up doing, I just wish I didn't have to. Especially when I've got a whole lot of optional fields.

**Comment by lex-em** [comment]
Hi, @cowtowncoder does this problem solved? (without @JsonCreator and default value with Optional.empty())

**Comment by cowtowncoder** [comment]
@lex-em No. It is unlikely such behavior will get implemented, either.

**Comment by cowtowncoder** [comment]
As per earlier comments; this is possible with `@JsonCreator`, but not with other style properties.
If support for default values in general were added this could work, but it is not something that JDK8 module would support, and I think there is a separate databind issue for work, so closing this issue.
